version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
  loki:
    image: grafana/loki
    ports: ["3100:3100"]
  tempo:
    image: grafana/tempo
    ports: ["3200:3200"]
