version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finsight
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: ./backend
    env_file: .env.example
    depends_on: [db]
    ports: ["8080:8080"]
volumes:
  dbdata: {}
